# Predicting 2020 Presidential Outcomes by County based on 4 Factors: 
# Urban vs. Rural, Racial Diversity, Median Household Income, College Degrees

First, we import packages and preform exploratory data analysis. The data is taken from US census databases.

In [3]:
import pandas as pd
import numpy as np

In [4]:
density = pd.read_csv(r'/Users/cameronwalsmith/Desktop/Node/density.csv')

In [5]:
density.head()

,GISJOIN,STATE,STATEA,COUNTY,COUNTYA,CBSAA,METDIVA,CSAA,H7W001,H7W002,H7W003,H7W004,H7W005,H7W006
0,G0100010,Alabama,1,Autauga County,1,33860,99999,388,54571,31650,31650,0,22921,0
1,G0100030,Alabama,1,Baldwin County,3,19300,99999,380,182265,105205,63649,41556,77060,0
2,G0100050,Alabama,1,Barbour County,5,21640,99999,999,27457,8844,0,8844,18613,0
3,G0100070,Alabama,1,Bibb County,7,13820,99999,142,22915,7252,0,7252,15663,0
4,G0100090,Alabama,1,Blount County,9,13820,99999,142,57322,5760,386,5374,51562,0

In [6]:
density.shape

(3221, 14)

In [7]:
density.columns.values

array(['GISJOIN', 'STATE', 'STATEA', 'COUNTY', 'COUNTYA', 'CBSAA',
       'METDIVA', 'CSAA', 'H7W001', 'H7W002', 'H7W003', 'H7W004',
       'H7W005', 'H7W006'], dtype=object)

Here we assign a new column rural to equal the sum of H7W005 (population of county in area w/ < 2,500 residents) and H7W004 (population of county in area w/ 2,500 > 50,000 residents). This increased the accuracy of our model.

In [8]:
density['rural'] = density['H7W005'] + density['H7W004']
density.head()

,GISJOIN,STATE,STATEA,COUNTY,COUNTYA,CBSAA,METDIVA,CSAA,H7W001,H7W002,H7W003,H7W004,H7W005,H7W006,rural
0,G0100010,Alabama,1,Autauga County,1,33860,99999,388,54571,31650,31650,0,22921,0,22921
1,G0100030,Alabama,1,Baldwin County,3,19300,99999,380,182265,105205,63649,41556,77060,0,118616
2,G0100050,Alabama,1,Barbour County,5,21640,99999,999,27457,8844,0,8844,18613,0,27457
3,G0100070,Alabama,1,Bibb County,7,13820,99999,142,22915,7252,0,7252,15663,0,22915
4,G0100090,Alabama,1,Blount County,9,13820,99999,142,57322,5760,386,5374,51562,0,56936

Now we assign all counties where the population living in areas w/ >50,000 people is greater than that assigned to Rural to be "Urban"

In [9]:
density['class'] = np.where((density['H7W003'] >= density['rural']),
                           'Urban','Rural')
density.head(50)

,GISJOIN,STATE,STATEA,COUNTY,COUNTYA,CBSAA,METDIVA,CSAA,H7W001,H7W002,H7W003,H7W004,H7W005,H7W006,rural,class
0,G0100010,Alabama,1,Autauga County,1,33860,99999,388,54571,31650,31650,0,22921,0,22921,Urban
1,G0100030,Alabama,1,Baldwin County,3,19300,99999,380,182265,105205,63649,41556,77060,0,118616,Rural
2,G0100050,Alabama,1,Barbour County,5,21640,99999,999,27457,8844,0,8844,18613,0,27457,Rural
3,G0100070,Alabama,1,Bibb County,7,13820,99999,142,22915,7252,0,7252,15663,0,22915,Rural
4,G0100090,Alabama,1,Blount County,9,13820,99999,142,57322,5760,386,5374,51562,0,56936,Rural
5,G0100110,Alabama,1,Bullock County,11,99999,99999,999,10914,5307,0,5307,5607,0,10914,Rural
6,G0100130,Alabama,1,Butler County,13,99999,99999,999,20947,6026,0,6026,14921,0,20947,Rural
7,G0100150,Alabama,1,Calhoun County,15,11500,99999,999,118572,78617,74951,3666,39955,0,43621,Urban
8,G0100170,Alabama,1,Chambers County,17,46740,99999,122,34215,17399,0,17399,16816,0,34215,Rural
9,G0100190,Alabama,1,Cherokee County,19,99999,99999,999,25989,3707,0,3707,22282,0,25989,Rural
10,G0100210,Alabama,1,Chilton County,21,13820,99999,142,43643,5785,0,5785,37858,0,43643,Rural
11,G0100230,Alabama,1,Choctaw County,23,99999,99999,999,13859,0,0,0,13859,0,13859,Rural
12,G0100250,Alabama,1,Clarke County,25,99999,99999,999,25833,6205,0,6205,19628,0,25833,Rural
13,G0100270,Alabama,1,Clay County,27,99999,99999,999,13932,0,0,0,13932,0,13932,Rural
14,G0100290,Alabama,1,Cleburne County,29,99999,99999,999,14972,0,0,0,14972,0,14972,Rural
15,G0100310,Alabama,1,Coffee County,31,21460,99999,222,49948,26375,0,26375,23573,0,49948,Rural
16,G0100330,Alabama,1,Colbert County,33,22520,99999,999,54428,30537,30066,471,23891,0,24362,Urban
17,G0100350,Alabama,1,Conecuh County,35,99999,99999,999,13228,2520,0,2520,10708,0,13228,Rural
18,G0100370,Alabama,1,Coosa County,37,10760,99999,388,11539,0,0,0,11539,0,11539,Rural
19,G0100390,Alabama,1,Covington County,39,99999,99999,999,37765,11461,0,11461,26304,0,37765,Rural
20,G0100410,Alabama,1,Crenshaw County,41,99999,99999,999,13906,0,0,0,13906,0,13906,Rural
21,G0100430,Alabama,1,Cullman County,43,18980,99999,142,80406,21517,0,21517,58889,0,80406,Rural
22,G0100450,Alabama,1,Dale County,45,21460,99999,222,50251,24679,2561,22118,25572,0,47690,Rural
23,G0100470,Alabama,1,Dallas County,47,42820,99999,999,43820,23821,0,23821,19999,0,43820,Rural
24,G0100490,Alabama,1,DeKalb County,49,22840,99999,999,71109,7018,0,7018,64091,0,71109,Rural
25,G0100510,Alabama,1,Elmore County,51,33860,99999,388,79303,36330,26957,9373,42973,0,52346,Rural
26,G0100530,Alabama,1,Escambia County,53,99999,99999,999,38319,13982,0,13982,24337,0,38319,Rural
27,G0100550,Alabama,1,Etowah County,55,23460,99999,999,104430,65286,64141,1145,39144,0,40289,Urban
28,G0100570,Alabama,1,Fayette County,57,99999,99999,999,17241,3408,0,3408,13833,0,17241,Rural
29,G0100590,Alabama,1,Franklin County,59,99999,99999,999,31704,9395,0,9395,22309,0,31704,Rural
30,G0100610,Alabama,1,Geneva County,61,20020,99999,222,26790,2775,121,2654,24015,0,26669,Rural
31,G0100630,Alabama,1,Greene County,63,46220,99999,999,9045,0,0,0,9045,0,9045,Rural
32,G0100650,Alabama,1,Hale County,65,46220,99999,999,15760,1707,0,1707,14053,0,15760,Rural
33,G0100670,Alabama,1,Henry County,67,20020,99999,222,17302,2119,0,2119,15183,0,17302,Rural
34,G0100690,Alabama,1,Houston County,69,20020,99999,222,101547,67220,66099,1121,34327,0,35448,Urban
35,G0100710,Alabama,1,Jackson County,71,42460,99999,999,53227,12233,0,12233,40994,0,53227,Rural
36,G0100730,Alabama,1,Jefferson County,73,13820,99999,142,658466,593714,592559,1155,64752,0,65907,Urban
37,G0100750,Alabama,1,Lamar County,75,99999,99999,999,14564,0,0,0,14564,0,14564,Rural
38,G0100770,Alabama,1,Lauderdale County,77,22520,99999,999,92709,47008,47008,0,45701,0,45701,Urban
39,G0100790,Alabama,1,Lawrence County,79,19460,99999,290,34339,2991,72,2919,31348,0,34267,Rural
40,G0100810,Alabama,1,Lee County,81,12220,99999,194,140247,101806,101806,0,38441,0,38441,Urban
41,G0100830,Alabama,1,Limestone County,83,26620,99999,290,82782,35092,10136,24956,47690,0,72646,Rural
42,G0100850,Alabama,1,Lowndes County,85,33860,99999,388,11299,0,0,0,11299,0,11299,Rural
43,G0100870,Alabama,1,Macon County,87,46260,99999,194,21452,9536,0,9536,11916,0,21452,Rural
44,G0100890,Alabama,1,Madison County,89,26620,99999,290,334811,279763,276556,3207,55048,0,58255,Urban
45,G0100910,Alabama,1,Marengo County,91,99999,99999,999,21027,6452,0,6452,14575,0,21027,Rural
46,G0100930,Alabama,1,Marion County,93,99999,99999,999,30776,3430,0,3430,27346,0,30776,Rural
47,G0100950,Alabama,1,Marshall County,95,10700,99999,999,93019,43469,0,43469,49550,0,93019,Rural
48,G0100970,Alabama,1,Mobile County,97,33660,99999,380,412992,330310,326183,4127,82682,0,86809,Urban
49,G0100990,Alabama,1,Monroe County,99,99999,99999,999,23068,4834,0,4834,18234,0,23068,Rural

In [10]:
income = pd.read_csv(r'/Users/cameronwalsmith/Desktop/Node/income.csv')

In [11]:
income.shape

(3220, 8)

In [12]:
income.columns.values

array(['GISJOIN', 'YEAR', 'STATE', 'STATEA', 'COUNTY', 'COUNTYA',
       'NAME_E', 'AJZAE001'], dtype=object)

In [13]:
income.head()

,GISJOIN,YEAR,STATE,STATEA,COUNTY,COUNTYA,NAME_E,AJZAE001
0,G0100010,2014-2018,Alabama,1,Autauga County,1,"Autauga County, Alabama",58786.0
1,G0100030,2014-2018,Alabama,1,Baldwin County,3,"Baldwin County, Alabama",55962.0
2,G0100050,2014-2018,Alabama,1,Barbour County,5,"Barbour County, Alabama",34186.0
3,G0100070,2014-2018,Alabama,1,Bibb County,7,"Bibb County, Alabama",45340.0
4,G0100090,2014-2018,Alabama,1,Blount County,9,"Blount County, Alabama",48695.0

In [14]:
race = pd.read_csv(r'/Users/cameronwalsmith/Desktop/Node/race.csv')

In [15]:
race.shape

(3220, 16)

In [16]:
race.columns.values

array(['GISJOIN', 'STATE', 'STATEA', 'COUNTY', 'COUNTYA', 'NAME_E',
       'AJWNE001', 'AJWNE002', 'AJWNE003', 'AJWNE004', 'AJWNE005',
       'AJWNE006', 'AJWNE007', 'AJWNE008', 'AJWNE009', 'AJWNE010'],
      dtype=object)

In [17]:
race.head()

,GISJOIN,STATE,STATEA,COUNTY,COUNTYA,NAME_E,AJWNE001,AJWNE002,AJWNE003,AJWNE004,AJWNE005,AJWNE006,AJWNE007,AJWNE008,AJWNE009,AJWNE010
0,G0100010,Alabama,1,Autauga County,1,"Autauga County, Alabama",55200,42437,10565,159,568,32,409,1030,18,1012
1,G0100030,Alabama,1,Baldwin County,3,"Baldwin County, Alabama",208107,179526,19764,1522,1680,9,2034,3572,603,2969
2,G0100050,Alabama,1,Barbour County,5,"Barbour County, Alabama",25782,12216,12266,72,96,1,778,353,22,331
3,G0100070,Alabama,1,Bibb County,7,"Bibb County, Alabama",22527,17268,5018,8,37,0,9,187,0,187
4,G0100090,Alabama,1,Blount County,9,"Blount County, Alabama",57645,55054,862,141,198,18,437,935,31,904

Here we assign a column indicated proportion of county that is White, or White Population / Total Population

In [18]:
race['white proportion'] = race.AJWNE002 / race.AJWNE001
race.head()

,GISJOIN,STATE,STATEA,COUNTY,COUNTYA,NAME_E,AJWNE001,AJWNE002,AJWNE003,AJWNE004,AJWNE005,AJWNE006,AJWNE007,AJWNE008,AJWNE009,AJWNE010,white proportion
0,G0100010,Alabama,1,Autauga County,1,"Autauga County, Alabama",55200,42437,10565,159,568,32,409,1030,18,1012,0.768786
1,G0100030,Alabama,1,Baldwin County,3,"Baldwin County, Alabama",208107,179526,19764,1522,1680,9,2034,3572,603,2969,0.862662
2,G0100050,Alabama,1,Barbour County,5,"Barbour County, Alabama",25782,12216,12266,72,96,1,778,353,22,331,0.473819
3,G0100070,Alabama,1,Bibb County,7,"Bibb County, Alabama",22527,17268,5018,8,37,0,9,187,0,187,0.766547
4,G0100090,Alabama,1,Blount County,9,"Blount County, Alabama",57645,55054,862,141,198,18,437,935,31,904,0.955052

In [19]:
education = pd.read_csv(r'/Users/cameronwalsmith/Desktop/Node/education.csv')

In [20]:
education.shape

(3220, 31)

In [21]:
education.columns.values

array(['GISJOIN', 'STATE', 'STATEA', 'COUNTY', 'Unnamed: 4', 'NAME_E',
       'AJYPE001', 'AJYPE002', 'AJYPE003', 'AJYPE004', 'AJYPE005',
       'AJYPE006', 'AJYPE007', 'AJYPE008', 'AJYPE009', 'AJYPE010',
       'AJYPE011', 'AJYPE012', 'AJYPE013', 'AJYPE014', 'AJYPE015',
       'AJYPE016', 'AJYPE017', 'AJYPE018', 'AJYPE019', 'AJYPE020',
       'AJYPE021', 'AJYPE022', 'AJYPE023', 'AJYPE024', 'AJYPE025'],
      dtype=object)

In [22]:
education.head()

,GISJOIN,STATE,STATEA,COUNTY,Unnamed: 4,NAME_E,AJYPE001,AJYPE002,AJYPE003,AJYPE004,...,AJYPE016,AJYPE017,AJYPE018,AJYPE019,AJYPE020,AJYPE021,AJYPE022,AJYPE023,AJYPE024,AJYPE025
0,G0100010,Alabama,1,Autauga County,1,"Autauga County, Alabama",37166,287,0,0,...,667,10104,2015,2235,5319,2998,5903,3406,510,472
1,G0100030,Alabama,1,Baldwin County,3,"Baldwin County, Alabama",146989,1355,14,46,...,2264,33308,7271,9930,22336,13759,30431,11338,2992,1314
2,G0100050,Alabama,1,Barbour County,5,"Barbour County, Alabama",18173,380,4,0,...,575,5040,1446,1257,2030,1279,1417,606,92,105
3,G0100070,Alabama,1,Bibb County,7,"Bibb County, Alabama",15780,284,0,18,...,141,5996,1475,752,2186,908,1197,442,87,87
4,G0100090,Alabama,1,Blount County,9,"Blount County, Alabama",39627,692,12,2,...,808,11245,2244,2844,5648,4775,3217,1405,240,148

Here we add the population whos highest educational attainment is associates, bachelors, masters, doctoral or professional degrees, and divide that by total population.

In [25]:
education['degree'] = (education.AJYPE021 + education.AJYPE022 + education.AJYPE023 + education.AJYPE024 + education.AJYPE025) / education.AJYPE001
education.head()

,GISJOIN,STATE,STATEA,COUNTY,Unnamed: 4,NAME_E,AJYPE001,AJYPE002,AJYPE003,AJYPE004,...,AJYPE017,AJYPE018,AJYPE019,AJYPE020,AJYPE021,AJYPE022,AJYPE023,AJYPE024,AJYPE025,degree
0,G0100010,Alabama,1,Autauga County,1,"Autauga County, Alabama",37166,287,0,0,...,10104,2015,2235,5319,2998,5903,3406,510,472,0.357558
1,G0100030,Alabama,1,Baldwin County,3,"Baldwin County, Alabama",146989,1355,14,46,...,33308,7271,9930,22336,13759,30431,11338,2992,1314,0.407064
2,G0100050,Alabama,1,Barbour County,5,"Barbour County, Alabama",18173,380,4,0,...,5040,1446,1257,2030,1279,1417,606,92,105,0.192538
3,G0100070,Alabama,1,Bibb County,7,"Bibb County, Alabama",15780,284,0,18,...,5996,1475,752,2186,908,1197,442,87,87,0.172433
4,G0100090,Alabama,1,Blount County,9,"Blount County, Alabama",39627,692,12,2,...,11245,2244,2844,5648,4775,3217,1405,240,148,0.246928

# Preprocessing the Data

Now we drop columns that are irrelivant to the merge

In [26]:
df = pd.merge(density, income.drop(columns=['STATE','YEAR','STATE','STATEA','COUNTY','COUNTYA','NAME_E']), on='GISJOIN')
df.head()

,GISJOIN,STATE,STATEA,COUNTY,COUNTYA,CBSAA,METDIVA,CSAA,H7W001,H7W002,H7W003,H7W004,H7W005,H7W006,rural,class,AJZAE001
0,G0100010,Alabama,1,Autauga County,1,33860,99999,388,54571,31650,31650,0,22921,0,22921,Urban,58786.0
1,G0100030,Alabama,1,Baldwin County,3,19300,99999,380,182265,105205,63649,41556,77060,0,118616,Rural,55962.0
2,G0100050,Alabama,1,Barbour County,5,21640,99999,999,27457,8844,0,8844,18613,0,27457,Rural,34186.0
3,G0100070,Alabama,1,Bibb County,7,13820,99999,142,22915,7252,0,7252,15663,0,22915,Rural,45340.0
4,G0100090,Alabama,1,Blount County,9,13820,99999,142,57322,5760,386,5374,51562,0,56936,Rural,48695.0

In [27]:
df2 = pd.merge(df, race.drop(columns=['STATE','STATEA','COUNTY','COUNTYA','NAME_E']), on='GISJOIN')
df2.head()

,GISJOIN,STATE,STATEA,COUNTY,COUNTYA,CBSAA,METDIVA,CSAA,H7W001,H7W002,...,AJWNE002,AJWNE003,AJWNE004,AJWNE005,AJWNE006,AJWNE007,AJWNE008,AJWNE009,AJWNE010,white proportion
0,G0100010,Alabama,1,Autauga County,1,33860,99999,388,54571,31650,...,42437,10565,159,568,32,409,1030,18,1012,0.768786
1,G0100030,Alabama,1,Baldwin County,3,19300,99999,380,182265,105205,...,179526,19764,1522,1680,9,2034,3572,603,2969,0.862662
2,G0100050,Alabama,1,Barbour County,5,21640,99999,999,27457,8844,...,12216,12266,72,96,1,778,353,22,331,0.473819
3,G0100070,Alabama,1,Bibb County,7,13820,99999,142,22915,7252,...,17268,5018,8,37,0,9,187,0,187,0.766547
4,G0100090,Alabama,1,Blount County,9,13820,99999,142,57322,5760,...,55054,862,141,198,18,437,935,31,904,0.955052

In [28]:
df3 = pd.merge(df2, education.drop(columns=['STATE','STATE','STATEA','COUNTY','Unnamed: 4','NAME_E']), on='GISJOIN')
df3.head()

,GISJOIN,STATE,STATEA,COUNTY,COUNTYA,CBSAA,METDIVA,CSAA,H7W001,H7W002,...,AJYPE017,AJYPE018,AJYPE019,AJYPE020,AJYPE021,AJYPE022,AJYPE023,AJYPE024,AJYPE025,degree
0,G0100010,Alabama,1,Autauga County,1,33860,99999,388,54571,31650,...,10104,2015,2235,5319,2998,5903,3406,510,472,0.357558
1,G0100030,Alabama,1,Baldwin County,3,19300,99999,380,182265,105205,...,33308,7271,9930,22336,13759,30431,11338,2992,1314,0.407064
2,G0100050,Alabama,1,Barbour County,5,21640,99999,999,27457,8844,...,5040,1446,1257,2030,1279,1417,606,92,105,0.192538
3,G0100070,Alabama,1,Bibb County,7,13820,99999,142,22915,7252,...,5996,1475,752,2186,908,1197,442,87,87,0.172433
4,G0100090,Alabama,1,Blount County,9,13820,99999,142,57322,5760,...,11245,2244,2844,5648,4775,3217,1405,240,148,0.246928

In [29]:
results = pd.read_csv('https://raw.githubusercontent.com/favstats/USElection2020-NYT-Results/master/data/2020-11-11%2000-33-25/presidential/presidential.csv')

In [30]:
results.shape

(3159, 106)

In [31]:
results.columns.values

array(['fips', 'name', 'votes', 'absentee_votes', 'reporting',
       'precincts', 'absentee_method', 'eevp', 'tot_exp_vote',
       'eevp_value', 'eevp_display', 'eevp_source', 'turnout_stage',
       'absentee_count_progress', 'absentee_outstanding',
       'absentee_max_ballots', 'provisional_outstanding',
       'provisional_count_progress', 'results_trumpd', 'results_bidenj',
       'results_jorgensenj', 'results_venturaj', 'results_pierceb',
       'results_blankenshipd', 'results_de_la_fuenter',
       'results_write_ins', 'results_absentee_trumpd',
       'results_absentee_bidenj', 'results_absentee_jorgensenj',
       'results_absentee_venturaj', 'results_absentee_pierceb',
       'results_absentee_blankenshipd', 'results_absentee_de_la_fuenter',
       'results_absentee_write_ins', 'last_updated',
       'leader_margin_value', 'leader_margin_display',
       'leader_margin_name_display', 'leader_party_id', 'margin2020',
       'state', 'retrieved_time', 'results_hawkinsh',
       'results_absentee_hawkinsh', 'votes2016', 'margin2016',
       'votes2012', 'margin2012', 'results_westk', 'results_kennedya',
       'results_la_rivag', 'results_absentee_westk',
       'results_absentee_kennedya', 'results_absentee_la_rivag',
       'results_carrollb', 'results_absentee_carrollb',
       'results_simmonsj', 'results_boddiep', 'results_hammonsb',
       'results_hoeflingt', 'results_absentee_simmonsj',
       'results_absentee_boddiep', 'results_absentee_hammonsb',
       'results_absentee_hoeflingt', 'results_collinsp',
       'results_absentee_collinsp', 'results_kingr',
       'results_absentee_kingr', 'results_segalj',
       'results_absentee_segalj', 'results_gammonc', 'results_myersj',
       'results_absentee_gammonc', 'results_absentee_myersj',
       'results_paigeh', 'results_lafontainec', 'results_duncanr',
       'results_mccormick', 'results_huberb', 'results_kopitkek',
       'results_swingg', 'results_scalfz', 'results_absentee_paigeh',
       'results_absentee_lafontainec', 'results_absentee_duncanr',
       'results_absentee_mccormick', 'results_absentee_huberb',
       'results_absentee_kopitkek', 'results_absentee_swingg',
       'results_absentee_scalfz', 'results_hunterd',
       'results_absentee_hunterd', 'results_none_of_these_candidates',
       'results_absentee_none_of_these_candidates', 'results_tittles',
       'results_absentee_tittles', 'results_charlesm', 'results_mchughj',
       'results_jacob_fambrop', 'results_scottj', 'results_kishorej',
       'results_absentee_charlesm', 'results_absentee_mchughj',
       'results_absentee_jacob_fambrop', 'results_absentee_scottj',
       'results_absentee_kishorej'], dtype=object)

This is the 2020 Presidential results by county

In [32]:
results.head()

,fips,name,votes,absentee_votes,reporting,precincts,absentee_method,eevp,tot_exp_vote,eevp_value,...,results_charlesm,results_mchughj,results_jacob_fambrop,results_scottj,results_kishorej,results_absentee_charlesm,results_absentee_mchughj,results_absentee_jacob_fambrop,results_absentee_scottj,results_absentee_kishorej
0,2901,ED 1,4251,955,5,9,Released as a separate subtotal as first repor...,56.0,7634.0,56%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2910,ED 10,4886,1369,5,11,Released as a separate subtotal as first repor...,47.0,10396.0,47%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2911,ED 11,5196,2441,4,9,Released as a separate subtotal as first repor...,47.0,11142.0,47%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2912,ED 12,2309,1365,1,7,Released as a separate subtotal as first repor...,21.0,10974.0,21%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2913,ED 13,3229,281,3,6,Released as a separate subtotal as first repor...,43.0,7513.0,43%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [33]:
results_cols = results[['fips', 'leader_party_id']]
results_cols.head()

   fips leader_party_id
0  2901      republican
1  2910      republican
2  2911      republican
3  2912      republican
4  2913      republican

The results dataset was organized by FIPS, an individual number assigned to every county in the US. To align the results with our census data, we had to use another dataset that assigned FIPS to each county, and then play with the wording to match the names in all datasheets

In [34]:
fips = pd.read_csv('https://raw.githubusercontent.com/kjhealy/fips-codes/master/county_fips_master.csv', encoding = "ISO-8859-1")

In [35]:
fips.shape

(3146, 13)

In [36]:
fips.columns.values

array(['fips', 'county_name', 'state_abbr', 'state_name', 'long_name',
       'sumlev', 'region', 'division', 'state', 'county', 'crosswalk',
       'region_name', 'division_name'], dtype=object)

In [37]:
fips.head()

,fips,county_name,state_abbr,state_name,long_name,sumlev,region,division,state,county,crosswalk,region_name,division_name
0,1001,Autauga County,AL,Alabama,Autauga County AL,50.0,3.0,6.0,1.0,1.0,3-6-1-1,South,East South Central
1,1003,Baldwin County,AL,Alabama,Baldwin County AL,50.0,3.0,6.0,1.0,3.0,3-6-1-3,South,East South Central
2,1005,Barbour County,AL,Alabama,Barbour County AL,50.0,3.0,6.0,1.0,5.0,3-6-1-5,South,East South Central
3,1007,Bibb County,AL,Alabama,Bibb County AL,50.0,3.0,6.0,1.0,7.0,3-6-1-7,South,East South Central
4,1009,Blount County,AL,Alabama,Blount County AL,50.0,3.0,6.0,1.0,9.0,3-6-1-9,South,East South Central

In [38]:
fips_cols = fips[['fips', 'county_name', 'state_name']]
fips_cols.head()

   fips     county_name state_name
0  1001  Autauga County    Alabama
1  1003  Baldwin County    Alabama
2  1005  Barbour County    Alabama
3  1007     Bibb County    Alabama
4  1009   Blount County    Alabama

In [39]:
all_results = pd.merge(results_cols, fips_cols, on='fips', how='inner')

In [40]:
all_results.head()

    fips leader_party_id      county_name state_name
0  48001      republican  Anderson County      Texas
1  48003      republican   Andrews County      Texas
2  48005      republican  Angelina County      Texas
3  48007      republican   Aransas County      Texas
4  48009      republican    Archer County      Texas

In [41]:
all_results.drop_duplicates(subset=['fips'])

       fips leader_party_id           county_name            state_name
0     48001      republican       Anderson County                 Texas
1     48003      republican        Andrews County                 Texas
2     48005      republican       Angelina County                 Texas
3     48007      republican        Aransas County                 Texas
4     48009      republican         Archer County                 Texas
...     ...             ...                   ...                   ...
3107  49057      republican          Weber County                  Utah
3108  10001        democrat           Kent County              Delaware
3109  10003        democrat     New Castle County              Delaware
3110  10005      republican         Sussex County              Delaware
3111  11001        democrat  District of Columbia  District of Columbia

[3112 rows x 4 columns]

In [42]:
all_results['county'] = all_results['county_name'] + ", " + all_results['state_name']

In [43]:
all_results.head()

    fips leader_party_id      county_name state_name                  county
0  48001      republican  Anderson County      Texas  Anderson County, Texas
1  48003      republican   Andrews County      Texas   Andrews County, Texas
2  48005      republican  Angelina County      Texas  Angelina County, Texas
3  48007      republican   Aransas County      Texas   Aransas County, Texas
4  48009      republican    Archer County      Texas    Archer County, Texas

In [44]:
election_results = all_results.drop(columns=['county_name', 'state_name'])

In [45]:
election_results.head()

    fips leader_party_id                  county
0  48001      republican  Anderson County, Texas
1  48003      republican   Andrews County, Texas
2  48005      republican  Angelina County, Texas
3  48007      republican   Aransas County, Texas
4  48009      republican    Archer County, Texas

In [46]:
df3.head()

,GISJOIN,STATE,STATEA,COUNTY,COUNTYA,CBSAA,METDIVA,CSAA,H7W001,H7W002,...,AJYPE017,AJYPE018,AJYPE019,AJYPE020,AJYPE021,AJYPE022,AJYPE023,AJYPE024,AJYPE025,degree
0,G0100010,Alabama,1,Autauga County,1,33860,99999,388,54571,31650,...,10104,2015,2235,5319,2998,5903,3406,510,472,0.357558
1,G0100030,Alabama,1,Baldwin County,3,19300,99999,380,182265,105205,...,33308,7271,9930,22336,13759,30431,11338,2992,1314,0.407064
2,G0100050,Alabama,1,Barbour County,5,21640,99999,999,27457,8844,...,5040,1446,1257,2030,1279,1417,606,92,105,0.192538
3,G0100070,Alabama,1,Bibb County,7,13820,99999,142,22915,7252,...,5996,1475,752,2186,908,1197,442,87,87,0.172433
4,G0100090,Alabama,1,Blount County,9,13820,99999,142,57322,5760,...,11245,2244,2844,5648,4775,3217,1405,240,148,0.246928

In [47]:
df3['county_name'] = df3['COUNTY'] + ", " + df3['STATE']

In [48]:
df3.head()

,GISJOIN,STATE,STATEA,COUNTY,COUNTYA,CBSAA,METDIVA,CSAA,H7W001,H7W002,...,AJYPE018,AJYPE019,AJYPE020,AJYPE021,AJYPE022,AJYPE023,AJYPE024,AJYPE025,degree,county_name
0,G0100010,Alabama,1,Autauga County,1,33860,99999,388,54571,31650,...,2015,2235,5319,2998,5903,3406,510,472,0.357558,"Autauga County, Alabama"
1,G0100030,Alabama,1,Baldwin County,3,19300,99999,380,182265,105205,...,7271,9930,22336,13759,30431,11338,2992,1314,0.407064,"Baldwin County, Alabama"
2,G0100050,Alabama,1,Barbour County,5,21640,99999,999,27457,8844,...,1446,1257,2030,1279,1417,606,92,105,0.192538,"Barbour County, Alabama"
3,G0100070,Alabama,1,Bibb County,7,13820,99999,142,22915,7252,...,1475,752,2186,908,1197,442,87,87,0.172433,"Bibb County, Alabama"
4,G0100090,Alabama,1,Blount County,9,13820,99999,142,57322,5760,...,2244,2844,5648,4775,3217,1405,240,148,0.246928,"Blount County, Alabama"

In [49]:
census = df3.drop(columns=['STATE', 'STATEA', 'COUNTY', 'COUNTYA', 'METDIVA', 'CBSAA', 'CSAA'])
census.head()

,GISJOIN,H7W001,H7W002,H7W003,H7W004,H7W005,H7W006,rural,class,AJZAE001,...,AJYPE018,AJYPE019,AJYPE020,AJYPE021,AJYPE022,AJYPE023,AJYPE024,AJYPE025,degree,county_name
0,G0100010,54571,31650,31650,0,22921,0,22921,Urban,58786.0,...,2015,2235,5319,2998,5903,3406,510,472,0.357558,"Autauga County, Alabama"
1,G0100030,182265,105205,63649,41556,77060,0,118616,Rural,55962.0,...,7271,9930,22336,13759,30431,11338,2992,1314,0.407064,"Baldwin County, Alabama"
2,G0100050,27457,8844,0,8844,18613,0,27457,Rural,34186.0,...,1446,1257,2030,1279,1417,606,92,105,0.192538,"Barbour County, Alabama"
3,G0100070,22915,7252,0,7252,15663,0,22915,Rural,45340.0,...,1475,752,2186,908,1197,442,87,87,0.172433,"Bibb County, Alabama"
4,G0100090,57322,5760,386,5374,51562,0,56936,Rural,48695.0,...,2244,2844,5648,4775,3217,1405,240,148,0.246928,"Blount County, Alabama"

In [50]:
new_census = census.drop_duplicates(subset=['county_name'])

In [51]:
election = election_results.drop_duplicates(subset=['county'])

In [52]:
df4 = pd.merge(new_census, election, left_on='county_name', right_on='county', how='inner')

In [53]:
print(election.loc[[1693]])

       fips leader_party_id                    county
1693  13143      republican  Haralson County, Georgia

In [54]:
df4.head()

,GISJOIN,H7W001,H7W002,H7W003,H7W004,H7W005,H7W006,rural,class,AJZAE001,...,AJYPE021,AJYPE022,AJYPE023,AJYPE024,AJYPE025,degree,county_name,fips,leader_party_id,county
0,G0100010,54571,31650,31650,0,22921,0,22921,Urban,58786.0,...,2998,5903,3406,510,472,0.357558,"Autauga County, Alabama",1001,republican,"Autauga County, Alabama"
1,G0100030,182265,105205,63649,41556,77060,0,118616,Rural,55962.0,...,13759,30431,11338,2992,1314,0.407064,"Baldwin County, Alabama",1003,republican,"Baldwin County, Alabama"
2,G0100050,27457,8844,0,8844,18613,0,27457,Rural,34186.0,...,1279,1417,606,92,105,0.192538,"Barbour County, Alabama",1005,republican,"Barbour County, Alabama"
3,G0100070,22915,7252,0,7252,15663,0,22915,Rural,45340.0,...,908,1197,442,87,87,0.172433,"Bibb County, Alabama",1007,republican,"Bibb County, Alabama"
4,G0100090,57322,5760,386,5374,51562,0,56936,Rural,48695.0,...,4775,3217,1405,240,148,0.246928,"Blount County, Alabama",1009,republican,"Blount County, Alabama"

In [55]:
df4.shape

(3070, 51)

In [56]:
df4.columns.values

array(['GISJOIN', 'H7W001', 'H7W002', 'H7W003', 'H7W004', 'H7W005',
       'H7W006', 'rural', 'class', 'AJZAE001', 'AJWNE001', 'AJWNE002',
       'AJWNE003', 'AJWNE004', 'AJWNE005', 'AJWNE006', 'AJWNE007',
       'AJWNE008', 'AJWNE009', 'AJWNE010', 'white proportion', 'AJYPE001',
       'AJYPE002', 'AJYPE003', 'AJYPE004', 'AJYPE005', 'AJYPE006',
       'AJYPE007', 'AJYPE008', 'AJYPE009', 'AJYPE010', 'AJYPE011',
       'AJYPE012', 'AJYPE013', 'AJYPE014', 'AJYPE015', 'AJYPE016',
       'AJYPE017', 'AJYPE018', 'AJYPE019', 'AJYPE020', 'AJYPE021',
       'AJYPE022', 'AJYPE023', 'AJYPE024', 'AJYPE025', 'degree',
       'county_name', 'fips', 'leader_party_id', 'county'], dtype=object)

In [57]:
df5 = df4.rename(columns={'leader_party_id':'target'}).drop(columns=['GISJOIN', 'county_name','county','fips', 'rural']).dropna()
df5.head()

,H7W001,H7W002,H7W003,H7W004,H7W005,H7W006,class,AJZAE001,AJWNE001,AJWNE002,...,AJYPE018,AJYPE019,AJYPE020,AJYPE021,AJYPE022,AJYPE023,AJYPE024,AJYPE025,degree,target
0,54571,31650,31650,0,22921,0,Urban,58786.0,55200,42437,...,2015,2235,5319,2998,5903,3406,510,472,0.357558,republican
1,182265,105205,63649,41556,77060,0,Rural,55962.0,208107,179526,...,7271,9930,22336,13759,30431,11338,2992,1314,0.407064,republican
2,27457,8844,0,8844,18613,0,Rural,34186.0,25782,12216,...,1446,1257,2030,1279,1417,606,92,105,0.192538,republican
3,22915,7252,0,7252,15663,0,Rural,45340.0,22527,17268,...,1475,752,2186,908,1197,442,87,87,0.172433,republican
4,57322,5760,386,5374,51562,0,Rural,48695.0,57645,55054,...,2244,2844,5648,4775,3217,1405,240,148,0.246928,republican

# Creating ML Model

In [58]:
df5['target'] = df5['target'].map({'republican':1,'democrat':0})
df5['class'] = df5['class'].map({'Urban':1,'Rural':0})

In [59]:
X = df5.drop(columns=['target'])
y = df5['target']

In [60]:
df5.columns.values
df5.isnull().sum()

H7W001              0
H7W002              0
H7W003              0
H7W004              0
H7W005              0
H7W006              0
class               0
AJZAE001            0
AJWNE001            0
AJWNE002            0
AJWNE003            0
AJWNE004            0
AJWNE005            0
AJWNE006            0
AJWNE007            0
AJWNE008            0
AJWNE009            0
AJWNE010            0
white proportion    0
AJYPE001            0
AJYPE002            0
AJYPE003            0
AJYPE004            0
AJYPE005            0
AJYPE006            0
AJYPE007            0
AJYPE008            0
AJYPE009            0
AJYPE010            0
AJYPE011            0
AJYPE012            0
AJYPE013            0
AJYPE014            0
AJYPE015            0
AJYPE016            0
AJYPE017            0
AJYPE018            0
AJYPE019            0
AJYPE020            0
AJYPE021            0
AJYPE022            0
AJYPE023            0
AJYPE024            0
AJYPE025            0
degree              0
target              0
dtype: int64

In [61]:
from IPython.display import display_html
def display_side_by_side(*args):
    html_str=''
    for df in args:
        html_str+=df.to_html()
    display_html(html_str.replace('table','table style=\"display:inline\"'),raw=True)

In [62]:
display_side_by_side(X.iloc[:5,:9],pd.DataFrame(y).head())

In [63]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [64]:
from sklearn import svm
clf = svm.SVC()

In [65]:
clf.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [66]:
predicted = clf.predict(X_test)
actual = np.array(y_test)

print('Look at first 10 predictions:')
print('Predicted: ',predicted[:10])
print('Actual:    ',actual[:10])

Look at first 10 predictions:
Predicted:  [1 1 1 1 1 1 1 1 1 1]
Actual:     [1 0 1 1 1 0 1 1 1 1]

In [67]:
from sklearn.metrics import accuracy_score

# Evaluating Model Preformance

In [68]:
accuracy_score(predicted,actual)

0.8631921824104235